spring:
    application:
        name: TestApp
    #   GraphQL configs
    graphql:
        graphiql:
            enabled: true
            path: /graphiql
    r2dbc:
        url: r2dbc:mysql://localhost:3306/friendsmanagement
        username: "user"
        password: "password"
    #   JPA
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
    #    Datasource
#    datasource:
#        url: jdbc:mysql://localhost:3306/friendsmanagement
#        username: root
#        password: Now123DQN
#        driver-class-name: com.mysql.cj.jdbc.Driver

