spring:
    application:
        name: TestApp
    #   GraphQL configs
    graphql:
        graphiql:
            enabled: true
            path: /graphiql
    r2dbc:
        url: r2dbc:mysql://localhost:3306/friendsmanagement
        username: "root"
        password: "A%9jr>NK"
    #   JPA
    jpa:
        hibernate:
            ddl-auto: none
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

